---
title: "Models for Marine Ecosystem-Based Management"
author: "Gavin Fay"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "This is a CINAR-supported training course at UMass Dartmouth to be offered fall semester 2022"
---

# Welcome {.unnumbered}

*Models for Marine Ecosystem-Based Management*: Hello! This is a course taught by Dr. Gavin Fay at UMass Dartmouth in fall 2022. The course is supported through Dr. Fay's CINAR fellowship in Quantitative Fisheries and Ecosystem Science. Course can be attended by students and staff at CINAR institutions and all UMass campuses (if you are not at one of these institutions but are interested in the class please [email Gavin](mailto:gfay@umassd.edu)).

**Description**: This course provides instruction, demonstration, and exercises in quantitative modeling tools used for Ecosystem Based Management (EBM) of living marine resources. There is an increasing need for fisheries and wildlife professionals to provide scientific advice for management in an ecosystem context. Part 1 of the course will provide students with hands on experience applying fisheries stock assessment and population models that include ecosystem effects, and consider the policy implications of including this information. Part 2 of the course will focus on broader multiple-use and human dimensions and include economic and behavioral models and models for marine spatial planning. The final section of the course will introduce whole-of-ecosystem models and demonstrate how these can be used to provide strategic advice for marine management and consider a broad suite of objectives. Although the examples used will be in a marine context, the types of models and methods discussed in the course have application in other systems.

**Course Objectives**: 1. Familiarity with a range of models used for ecosystem-based management and experience using some of them. 2. Understanding of the benefits, challenges, and limitations of using these models to provide scientific advice for management.

**Code of Conduct**; These workshops follow the [Fay Lab code of conduct:](https://thefaylab.github.io/lab-manual/code)

------------------------------------------------------------------------

## Agenda {.unnumbered}

*(subject to change)*

| Date   | Week | Day | Topic                                                      |
|---------------|---------------|---------------|---------------------------|
| 1-Sep  | 1    | Th  | Software installation troubleshooting (9am)                |
| 1-Sep  | 1    | Th  | Introductory material, fisheries assessment methods review |
| 6-Sep  | 2    | T   | [TMB Workshop I](#tmb) (9am)                               |
| 6-Sep  | 2    | T   | [TMB Workshop II](#tmb)                                    |
| 8-Sep  | 2    | Th  | [TMB Workshop III](#tmb) (9am)                             |
| 8-Sep  | 2    | Th  | [TMB Workshop IV](#tmb)                                    |
| 13-Sep | 3    | T   | Guest Lecure, Woods Hole Assessment Model (WHAM)           |
| 15-Sep | 3    | Th  | Extended Stock assessment models                           |
| 20-Sep | 4    | T   | Ecosystem Indicator Pressure-Response analyses             |
| 22-Sep | 4    | Th  | Guest Lecture, Joint Species Distribution Modeling         |
| 27-Sep | 5    | T   | Qualitative modeling                                       |
| 29-Sep | 5    | Th  | Multispecies models - estimating species interactions      |
| 4-Oct  | 6    | T   | Models of Intermediate Complexity for Ecosystems (MICE)    |
| 6-Oct  | 6    | Th  | WGSAM MSKEYRUNS REVIEW                                     |
| 11-Oct | 7    | T   | NO CLASS - MONDAY SCHEDULE                                 |
| 13-Oct | 7    | Th  | WGSAM                                                      |
| 18-Oct | 8    | T   | Fleet dynamics                                             |
| 20-Oct | 8    | Th  | Multispecies policy analysis - fishery ecosystem plans     |
| 25-Oct | 9    | T   | Guest Lecture, Dynamic Ocean Management                    |
| 27-Oct | 9    | Th  | Marine spatial planning                                    |
| 1-Nov  | 10   | T   | CAPAM stock assessment good practices                      |
| 3-Nov  | 10   | Th  | CAPAM stock assessment good practices                      |
| 8-Nov  | 11   | T   | Food web models I (Rpath module)                           |
| 10-Nov | 11   | Th  | Food web models II (Rpath module)                          |
| 15-Nov | 12   | T   | Ecosystem MSEs (Rpath module)                              |
| 17-Nov | 12   | Th  | Guest Lecture - Coupled ecosystem modeling                 |
| 22-Nov | 13   | T   | Whole of system models I                                   |
| 24-Nov | 13   | Th  | NO CLASS - THANKSGIVING                                    |
| 29-Nov | 14   | T   | Whole of system models 2                                   |
| 1-Dec  | 14   | Th  | Participatory modeling                                     |
| 6-Dec  | 15   | T   | Multicriteria Decision Analysis                            |
| 8-Dec  | 15   | Th  | NO CLASS                                                   |
| 13-Dec | 16   | T   | Project presentations                                      |

------------------------------------------------------------------------

**Class modality**: Current plan is for the course to be offered in person at UMassD-SMAST in New Bedford, with all course sessions also available for remote attendance via Zoom. There are two sub-module 'workshops' during the course - a TMB training in September, and a sequence of class sessions on the R implementation of Ecopath with Ecosim (EwE) foodweb modeling software, `Rpath`. Students who are interested in attending just one or both of these sub-modules should email Dr. Fay ASAP.

**Prerequisites**: Students should have taken coursework in applied statistics (e.g. MAR 535, Biological Statistics), or equivalent. Experience with the programming language R at the advanced beginner level is required (contact Dr. Fay if you would like recommendations for brief training materials that cover the necessary background). Students should also be familiar with modeling and estimation approaches for fisheries assessment and conservation management (e.g. MAR544), or seek permission from the instructor. While MAR530 (ecosystem-based fisheries management) provides useful background material for this class, it is not required.

**Homework assignments & Course Project**: 1. Five homework assignments (12% each). 2. Final project (40%). The aim of the project will be to apply some of the modeling methods covered during the course to a research-related task, and can be carried out individually or in small groups (2-3). For group projects, all group members must have readily-identifiable tasks and the same grade for the project will be assigned to all members of a group. Students are encouraged to select topics which are relevant to their thesis research and/or could form the basis for a short publication.

**Course materials**: This website (built in R!) provides access to the workshop materials and will be updated during the course as we progress (and adapt).

**This website**: <https://gavinfay.github.io/mebm-models/>\
**GitHub repo**: <https://github.com/gavinfay/mebm-models>

------------------------------------------------------------------------

**About the instructor**

[Gavin Fay](https://thefaylab.com) (he/him) is an Associate Professor of Fisheries Oceanography at the University of Massachusetts Dartmouth's School for Marine Science and Technology, based in New Bedford, MA. He is a 2020-2022 CINAR Fellow in Quantitative Fisheries & Ecosystem Science, funded through the NOAA Northeast Fisheries Science Center and NOAA Fisheries' Quantitative Ecology & Socioeconomics Training program (QUEST). This course is part of Dr. Fay's CINAR Fellowship activities. [Email](mailto:gfay@umassd.edu) [Twitter](https://twitter.com/gavin_fay)

------------------------------------------------------------------------

## Pre-course preparations {.unnumbered}

***Required hardware:*** Students should have use of a laptop computer for class sessions and assignments. Our class meetings will be a mix of lectures, discussions, and modeling, so it is necessary to have your computer at each meeting.

***Software:*** Our course exercises and modeling will primarily be done in R. You should install R and a suitable IDE (RStudio is one of the most common and will be how I work during the course).

If you already have R and RStudio installed on your machine, please take time before the course to install the latest versions, to help mitigate errors with installs and dependencies during the course. Using the most recent versions of these free software also gives you access to the most current functionality of the tools.

All of the course scripts, models, etc. will be tested using R 4.2.1. and RStudio 2022.07.1 (Build 554).

In addition to having R & RStudio downloaded on your machine, there will also be a RStudio Cloud project for the course, which will contain all necessary dependencies and packages used during the course.

[**Install R**](r-project.org)

[**Install RStudio**](https://www.rstudio.com/products/rstudio/)

Necessary libraries, and other pieces of software used in the course will be detailed in the relevant materials.

**Software installation session & TMB:** Gavin will run an optional software installation troubleshooting session at the beginning of the course on Thursday September 01, from 9:00-10:00 in SMAST-E 247. This would be a **GREAT** time to make sure TMB is working on your machine.

## Reading {.unnumbered}

A recommended reading list covering the individual topics will be posted on this website, as well as a Zotero database for the course. There is no required text for this class, though students will find sections of the following books useful.

-   Link, J. 2010. Ecosystem-based fisheries management: confronting tradeoffs. Cambridge Univ. Press, Cambridge.
-   McLeod, K., & Leslie, H. (Eds.). 2009. Ecosystem-based management for the oceans. Washington, DC, USA: Island Press.
-   Walters, C. J., & S.J. Martell. 2004. Fisheries ecology and management. Princeton University Press.

## Licensing {.unnumbered}

All materials are released with [Creative Commons Attribution Share Alike 4.0 International](LICENSE.md) license.

## Acknowledgements {.unnumbered}

This website is built with [bookdown](https://bookdown.org/)., and the lovely icons by [icons8](http://icons8.com/). The course website design was based on both the [R for Excel Users](https://rstudio-conf-2020.github.io/r-for-excel/) course by Julie Lowndes & Allison Horst, and the [Data Science in a Box](https://datasciencebox.org/) course by Mine Çetinkaya-Rundel, and previous course materials developed by Gavin Fay. All errors are purely by Gavin.
