# TMB Workshop {#tmb}

The first part of the course will be dedicated to an introductory training workshop to the statistical modeling software package Template Model Builder  (TMB), with additional class sessions.  

_TMB is an R package that provides quick implementation for fitting complex models to data, has many applications for statistical ecological modeling, and is becoming the standard method for implementing fisheries stock assessment models._

Condensing some of the software instruction part of the course into a more dense period has some advantages:  
1. a good way to learn is to be actively practicing; and with more focused sessions we can better help you get into a rhythm (we'll still be using examples relevant to the course, but this also helps to separate learning software from some other course objectives).  
2. there are a number of things going on in the fall that will disrupt our schedule (e.g. ICES annual science conference), and this is one way of ensuring you still get your money's worth for the course.  
3. there are others interested in TMB training and a short workshop format provides an easier way for these people to participate.  
4. this approach has seemed to work for me in the past, and for others who teach similar material.  

The sequence for the TMB training will be:  

09/01 9:00-10:00  Software installation troubleshooting session (not required)  
09/06 9:00-10:30  TMB workshop session 1  
09/06 1:00-2:30  TMB workshop session 2 (regular MAR 580 class time)  
09/08 9:00-10:30  TMB workshop session 3  
09/08 1:00-2:30  TMB workshop session 4 (regular MAR 580 class time)  


__Documentation__: The online [TMB book](https://kaskr.github.io/adcomp/_book/Introduction.html) is a great place to start.  

__RStudio Cloud__

A RStudio Cloud virtual machine has been set up for you to use in this workshop (though many may choose to run things locally on their own machines). Participants should see their emails for the logon link.  


## Materials {.unlisted .unnumbered}

A convenient way to access the code and materials is through the github repository for the TMB workshop, `mebm-tmb`, can be found at [https://github.com/gavinfay/mebm-tmb](https://github.com/gavinfay/mebm-tmb).  
You can download the repository from here using the green `Code` button.  
(ask Gavin how to clone the repo so you can pull in his changes later in the week!)  

## Session 1 {.unlisted .unnumbered}

__Introduction to TMB__

There is a Google Drive folder with all the [Session 1 materials](https://drive.google.com/drive/folders/1pEBz8RZBzev8iMI_ijGvBACRXjaCL6UJ?usp=sharing).  

[Intro lecture slide deck](https://docs.google.com/presentation/d/1qPjTXeEYLJuU4cAebFZveMKL_Z94PeG9/edit?usp=sharing&ouid=100082783551785338508&rtpof=true&sd=true)
[More TMB slide deck](https://docs.google.com/presentation/d/1SiRY6L-9jpAEKtGATnnEPlGNfL5VI3yQ/edit?usp=sharing&ouid=100082783551785338508&rtpof=true&sd=true)


## Session 2 {.unlisted .unnumbered}

__Mixed effects modeling in TMB__

Google Drive folder with all the [Session 2 materials](https://drive.google.com/drive/folders/1oQz5e-KHFiJZ16bHcABDDzJ1igN0zA9n?usp=sharing).  

[Mixed effects models lecture slide deck](https://docs.google.com/presentation/d/1a4q3weJTyZvrDZc0OMm5TRDXyA6M9emV/edit?usp=sharing&ouid=100082783551785338508&rtpof=true&sd=true)

## Session 3 {.unlisted .unnumbered}

__State-space modeling__

Google drive folder with [Session 3 materials](https://drive.google.com/drive/folders/1wgMkjTrhqRwqecwg4ujWKMOGHFg5OFZP?usp=sharing)

[slide deck](https://docs.google.com/presentation/d/1C3lRcbagWF8OlXsuxNvZmjI8pv18DOXD/edit?usp=sharing&ouid=100082783551785338508&rtpof=true&sd=true)


## Session 4 {.unlisted .unnumbered}

__spatial example and growth__

Google drive folder with [Session 4 materials](https://drive.google.com/drive/folders/1DCY7ZmewYbm1crumav_SzvpgeR1MQMHB?usp=sharing)

[slide deck](https://docs.google.com/presentation/d/1yAScOLKKXWUGlxg-c_eqqHljNyzMYPT8/edit?usp=sharing&ouid=100082783551785338508&rtpof=true&sd=true)



## Installation {.unlisted .unnumbered}

[These installation instructions](https://github.com/nwfsc-assess/geostatistical_delta-GLMM/wiki/Steps-to-install-TMB) are a good path for getting TMB installed on your machine. 

Note that for Windows users, you will need to install Rtools as part of the process.  

If you want to build TMB from source, including the development version, then you can follow the instructions on the [TMB repo here](https://github.com/kaskr/adcomp).  

__NOTE__ Our RStudio Cloud instance has TMB installed already, and so if you use this you do not have to worry about getting it working on your machine. (but you might want to for other uses)  


## Additional resources {.unlisted .unnumbered}

[lecture on probability](https://github.com/gavinfay/mebm-models/blob/main/course-materials/resources/lecture1B-probability.pdf)
[lecture on MLE](https://github.com/gavinfay/mebm-models/blob/main/course-materials/resources/lecture1C-likelihood.pdf)

