---
title: "CINAR MSE Workshop: First Multispecies MSE"
author: "Gavin Fay"
date: "January 2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
########  MS-PROD MSE Wrapper
########  Gavin Fay
########  Initially authored: July 2013
########  Modified by Andre Punt, March 2019
########  Modified again by Gavin, August 2021

datfile <- "Georges.dat"

#### dependencies
#install.packages('deSolve')
library(deSolve)

### MSPROD equation
## Solves the multsipecies operating model dynamics for a single time step given parameters, a set of harvest rates, and the current biomass
dNbydt <- function(t,N=1,parms=list(r=rep(0.4,length(N)),KGuild=rep(1,1),
                                    Ktot=10,alpha=matrix(0,nrow=1,ncol=1),
                                    Guildmembership=1,
                                    BetweenGuildComp=matrix(0,nrow=1,ncol=1),
                                    WithinGuildComp=matrix(0,nrow=1,ncol=1),hrate=0)) {
  NG <- aggregate(N,by=list(parms$Guildmembership),sum,na.rm=TRUE)$x
  NG <- t(parms$BetweenGuildComp)%*%NG
  KbyGuild <-parms$KGuild[parms$Guildmembership]

  predloss <-  parms$alpha%*%N*N
  cat <- parms$hrate*N
  betweenloss <- parms$r*N*NG[parms$Guildmembership]/(parms$Ktot-KbyGuild)
  withinloss <- parms$r*N*(parms$WithinGuildComp%*%N)/KbyGuild
  dN <- parms$r*N*(1-N/KbyGuild) - withinloss - betweenloss - predloss - cat
  results <- list(deriv=c(dN),catch=cat,predloss=predloss,withinloss=withinloss,betweenloss=betweenloss)
  return(results)
}

# ===============================================================================================

get.Indicators <- function(Biomass=NULL,Catch=NULL,size=NULL,trophic.level=NULL,BMSY=NULL,lifespan=NULL,is.predator=NULL,is.pelagic=NULL)
{
  # revenue
  Rev <- c(2,2,1,1,1,1,1,3,3,3)
  Nyr <- nrow(Biomass)
  Nsp <- ncol(Biomass)
  
  # Total system biomass summed over all species
  tot.bio <- rowSums(Biomass,na.rm=TRUE)
  # Total system catch summed over all species
  tot.cat <- rowSums(Catch,na.rm=TRUE)
  # Exploitation rate
  tot.rev <- rep(0,Nyr)
  for (Iyr in 1:Nyr) tot.rev[Iyr] <- sum(Catch[Iyr,]*Rev)
  exprate <- tot.cat/tot.bio
  # mean.length <- sum(Biomass*size,na.rm=TRUE)/sum(Biomass,na.rm=TRUE)
  # Trophic level of landings
  TL.landings <- rep(NA,nrow(Biomass))
  # Trophci level of survey
  TL.survey <- rep(NA,nrow(Biomass)) 
  # Proportion of total biomass that is comprised by predatory species
  prop.predators <- rowSums(Biomass[,is.predator],na.rm=TRUE)/tot.bio
  # Pelagic demersal ratio
  pd.ratio <- rowSums(Biomass[,is.pelagic],na.rm=TRUE)/rowSums(Biomass[,-(is.pelagic)],na.rm=TRUE)
  # Proportion of total biomass that is made of pelagic species
  prop.pel <- 1-(1/(pd.ratio+1))
  # Proportion of species that is overfished (less than half BMSY)
  prop.overfishedSp <- matrix(0,ncol=Nsp,nrow=Nyr)
  prop.overfished <- rep(NA,Nyr)
  for (i in 1:nrow(Biomass)) 
  {
    TL.landings[i] <- sum(trophic.level*Catch[i,],na.rm=TRUE)/sum(Catch[i,],na.rm=TRUE)
    TL.survey[i] <- sum(trophic.level*Biomass[i,],na.rm=TRUE)/sum(Biomass[i,],na.rm=TRUE)
    b.use <- Biomass[i,]
    prop.overfished[i] <- length(b.use[b.use<0.5*BMSY])/length(b.use)
    for (k in 1:Nsp)
     if (b.use[k] < 0.5*BMSY[k]) prop.overfishedSp[i,k] <- 1
  }
  # Rolling 10-year window of CVs (fill in)
  div.cv.bio <- rep(NA,nrow(Biomass))
  for (i in 10:nrow(Biomass))
    div.cv.bio[i] <- 1/(sd(tot.bio[((i-9):i)],na.rm=TRUE)/mean(tot.bio[((i-9):i)],na.rm=TRUE))
  results <- list(tot.bio=tot.bio,tot.cat=tot.cat,tot.rev=tot.rev,exprate=exprate,div.cv.bio=div.cv.bio,prop.overfished=prop.overfished,prop.pel=prop.pel,prop.predators=prop.predators,TL.landings=TL.landings,TL.survey=TL.survey,prop.overfishedSp=prop.overfishedSp)
  return(results)
}


# ===============================================================================================
# ===============================================================================================
```
get data

```{r}
#read in the base biological parameter values
datfile <- "Georges.dat"

#Number of species
Nsp <- scan(datfile,n=1,skip=3,quiet=T)
#guilds / functional groups
Guildmembership <- scan(datfile,n=Nsp,skip=9,quiet=T)
NGuild = length(unique(Guildmembership))
#Initial values
Initvals <- scan(datfile,n=Nsp,skip=13,quiet=T)
#carrying capacity for each guild
KGuild <- scan(datfile,n=NGuild,skip=17,quiet=T)
Ktot <- sum(KGuild)
cat("Spsecies/Guilds",Nsp,NGuild,"\n")

#growth rates
r <- scan(datfile,n=Nsp,skip=11,quiet=T)
#interactions
BetweenGuildComp <- matrix(scan(datfile,n=NGuild^2,skip=19,quiet=T),byrow=TRUE,nrow=NGuild)
WithinGuildComp <- matrix(scan(datfile,n=Nsp^2,skip=(20+NGuild)),byrow=TRUE,nrow=Nsp)
alpha <- matrix(scan(datfile,n=Nsp^2,skip=(21+NGuild+Nsp),quiet=T),byrow=TRUE,nrow=Nsp)
spatial.overlap <- matrix(scan(datfile,n=Nsp^2,skip=(22+NGuild+2*Nsp),quiet=T),byrow=TRUE,nrow=Nsp)
alpha <- alpha*spatial.overlap
# This is zero for this example
WithinGuildComp <- WithinGuildComp*spatial.overlap

# Reset harvest rates
hrate <- rep(0,Nsp)

#set values for BMSY
BMSY <- read.csv("Bmsy.csv",header=TRUE)
BMSY <- BMSY[c(4,5,21,22,14,23,24,6,3,7),]
BMSY[,2] <- KGuild/2
print(BMSY)

#initial biomass for each species
N <- Initvals
# Set projection horizon
Nyr <- 30
# Set the number of simulations
Nsims <- 5

### get historical time series of biomass and catch
NI <- read.table(datfile,skip=69,nrow=33,header=FALSE)
NI <- NI[,-1]
CI <- read.table(datfile,skip=103,nrow=33,header=FALSE)

#redefine functional groups
theguilds <- c(1,1,2,2,1,3,3,1,1,1)
```


```{r}
############################################
# RUN MSE WITH SINGLE SPECIES ASSESSMENT
############################################
#set up a storage object to contain results for each simulation
ALL.results <- matrix(NA,nrow=Nsims,ncol=4+Nsp)

#do a bunch of simulations
for (isim in 1:Nsims)
 {
  ### calculate values for ecological indicators at start of projection
  # AEP:IS BMSY correct
  ei <- get.Indicators(Biomass=NI,Catch=CI,BMSY=BMSY[,2],trophic.level=BMSY[,3],is.predator=which(colSums(alpha)>0),is.pelagic=which(theguilds==2)) 
  ei <- as.data.frame(ei)
  ei.new <- as.numeric(ei[nrow(ei),])
  names(ei.new) = colnames(ei)
  NI.obs <- NI
  CI.obs <- CI
  
  # Output reset
  SS.results <- NULL
  
  # do projection period
  for (iyr in 2:Nyr)
   {    
    ### hrateG is for groundfish; hrateP is for pelagics; hrateE is for elasmobranches
    Qyr2 <- nrow(NI.obs)
    #print(NI.obs)
    # hrate for groundfish depends on cod
    if (NI.obs[Qyr2,1] > 0.5*mean(NI.obs[1:10,1]))
     hrateG <- 0.1
    else
     hrateG <-0.1*NI.obs[Qyr2,1]/mean(NI.obs[1:10,1])
    # hrate for pelagics is 0.1 unless there is not enough prey
    if (NI.obs[Qyr2,4]+NI.obs[Qyr2,5] > 1000)
      hrateP <- 0.3
    else
      hrateP <- 0
    # hrate for sharks and skates is 0.05 unless we are approximately overfished
    if (NI.obs[Qyr2,7]+NI.obs[Qyr2,8] >  0.5*mean(NI.obs[1:10,7])+0.5*mean(NI.obs[1:10,8]))
      hrateE <- 0.05
    else
      hrateE <- 0

    hrate[theguilds==1] <- hrateG
    hrate[theguilds==2] <- hrateP
    hrate[theguilds==3] <- hrateE
    ### update operating model with new exploitation rates
    parms=list(r=r,KGuild=KGuild,Ktot=Ktot,Guildmembership=Guildmembership,BetweenGuildComp=BetweenGuildComp,WithinGuildComp=WithinGuildComp,alpha=alpha,hrate=hrate)
    x <- ode(N,seq(iyr-1,(iyr+0.5),0.5),dNbydt,parms=parms,method="rk4")

    # Extract N after one year and catches during the year; Rem is various losses
    N <- x[3,2:(Nsp+1)];N[N<=0] <- 0.01
    Cat <- 1.e-07+x[2,(Nsp+2):(2*Nsp+1)]; Cat[Cat<=0] <- 0.01
    Rem <- x[2,(2*Nsp+2):ncol(x)]

    ### store results for this time step
    SS.results <- rbind(SS.results,c(x[1,2:(Nsp+1)],x[2,(Nsp+2):ncol(x)]))
    if (iyr==Nyr) SS.results <- rbind(SS.results,c(x[3,2:(Nsp+1)],x[4,(Nsp+2):ncol(x)]))
    #generate data for this timestep and append to dataset
    Nobs <- N*exp(rnorm(10,0,0.2)-0.5*0.2*0.2)
    Cobs <- Cat
    NI.obs <- rbind(NI.obs,Nobs)
    CI.obs <- rbind(CI.obs,Cobs)
    
    #calculate ecological indicators based on new data at this time step
    # AEP:IS BMSY correct
    ei <- get.Indicators(Biomass=NI.obs,Catch=CI.obs,BMSY=BMSY[,2],trophic.level=BMSY[,3],is.predator=which(colSums(alpha)>0),is.pelagic=which(theguilds==2)) 
    ei <- as.data.frame(ei)
    ei.now <- as.numeric(ei[nrow(ei),])
    names(ei.now) = colnames(ei)
  }
 #print(ei)    
 colnames(SS.results)[1:Nsp] <- paste("Bio:",BMSY[,1],sep="")
 colnames(SS.results)[(Nsp+1):(2*Nsp)] <- paste("Catch:",BMSY[,1],sep="")
 SS.results <- SS.results[,1:(2*Nsp)]
 
 Qyr <- length(ei$tot.bio)
 ALL.results[isim,1] <- mean(ei$tot.bio[(Qyr-9):Qyr])
 ALL.results[isim,2] <- mean(ei$tot.cat[(Qyr-9):Qyr])
 ALL.results[isim,3] <- mean(ei$tot.rev[(Qyr-9):Qyr])
 ALL.results[isim,4] <- mean(ei$prop.overfished[(Qyr-9):Qyr])
 for (Isp in 1:Nsp)
   ALL.results[isim,4+Isp] <- sum(ei[(Qyr-9):Qyr,11+Isp])
 }
 print(ALL.results)
 cat("Expected total biomass:", mean(ALL.results[,1]),"\n")
 cat("Expected total catch:", mean(ALL.results[,2]),"\n")
 cat("Median revenue:", median(ALL.results[,3]),"\n")
 cat("Median revenue:", quantile(ALL.results[,3],prob=0.05),"\n")
 cat("Expected probability overfished:", mean(ALL.results[,4]),"\n")
 for (Isp in 1:Nsp)
  cat("Probability overfished:", as.character(BMSY[Isp,1]),mean(ALL.results[,4+Isp])/10,"\n")

```

